

export const SHUFFLE_ALL_DECKS = "SHUFFLE_ALL_DECKS";

export const DEAL_HEROES_TO_TOWN = "DEAL_HEROES_TO_TOWN";

export const DEAL_INITIAL_CARDS = "DEAL_INITIAL_CARDS";

export const NEXT_GAME_PHASE = "NEXT_GAME_PHASE";


